version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\projects\libofx-src
init:
- cmd: >-
    c:\msys64\usr\bin\bash -lc "echo MSYSTEM=%MSYSTEM% > /appveyor.environment"


environment:
  matrix:
  - MSYSTEM: MINGW32
  - MSYSTEM: MINGW64
install:
- cmd: >-
    c:\msys64\usr\bin\bash -lc "cd /c/projects/libofx-src/msys2 && ./appveyor-install.sh"

build_script:
- cmd: >-
    c:\msys64\usr\bin\bash -lc "cd /c/projects/libofx-src/msys2 && ./appveyor-build-opensp.sh"
    c:\msys64\usr\bin\bash -lc "cd /c/projects/libofx-src/msys2 && ./appveyor-build-ofx.sh"
    c:\msys64\usr\bin\bash -lc "ls /mingw*/share/glib-2.0/schemas/gschema.dtd"
artifacts:
- path: /libofx_MINGW32.zip
  name: libofx 32-bit
- path: /libofx_MING64.zip
  name: libofx 64-bit
