version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\projects\libofx-src
init:
- cmd: >-
    c:\msys64\usr\bin\bash -lc "echo MSYSTEM=%MSYSTEM% > /appveyor.environment"


environment:
  matrix:
  - MSYSTEM: MINGW32
  - MSYSTEM: MINGW64
install:
- cmd: >-
    c:\msys64\usr\bin\bash -lc "cd /c/projects/libofx-src/msys2 && ./appveyor-install.sh"

build_script:
- cmd: >-
    c:\msys64\usr\bin\bash -lc "cd /c/projects/libofx-src/msys2 && ./appveyor-build-opensp.sh"

    c:\msys64\usr\bin\bash -lc "cd /c/projects/libofx-src/msys2 && ./appveyor-build-ofx.sh"
artifacts:
- path: libofx_MINGW32.zip
  name: libofx 32-bit
- path: libofx_MINGW64.zip
  name: libofx 64-bit
deploy:
- provider: GitHub
  release: 1.5.2
  auth_token:
    secure: plZ0hq/bqPT4Ai678fOv6vh8AI3+hurTiGdAJaoHittds/K8yBDeUznuXoXNteaQ
  artifact: libofx 32-bit
  draft: true
  on:
    MSYSTEM: MINGW32
- provider: GitHub
  release: 1.5.2
  auth_token:
    secure: plZ0hq/bqPT4Ai678fOv6vh8AI3+hurTiGdAJaoHittds/K8yBDeUznuXoXNteaQ
  artifact: libofx 64-bit
  draft: true
  on:
    MSYSTEM: MINGW64
